############# Swedish navigation ##############

# main menu
[[main]]
name = "Hem"
url = "/"
weight = 1

[[main]]
name = "Om oss"
url = "/about"
weight = 2

[[main]]
name = "Produkter"
url = "/product"
weight = 3

[[main]]
name = "Tj채nster"
weight = 4
hasChildren = true

[[main]]
name = "Konsulting"
url = "/services"
parent = "Tj채nster"
weight = 1

[[main]]
name = "Portfolio"
url = "/portfolio"
parent = "Tj채nster"
weight = 2

[[main]]
name = "Blogg"
url = "/blog"
weight = 5

[[main]]
name = "Kontakt"
url = "/contact"
weight = 6


# footer menu
[[footer]]
name = "Om oss"
url = "/about"
weight = 1

[[footer]]
name = "Tj채nster"
url = "/services"
weight = 2

[[footer]]
name = "Kontakt"
url = "/contact"
weight = 3

[[footer]]
name = "Integritetspolicy"
url = "/privacy-policy"
weight = 4
