############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Platform"
url = "/platform"
weight = 2
hasChildren = true

[[main]]
name = "Publish"
url = "/platform/publish"
parent = "Platform"
weight = 1

[[main]]
name = "Spatial"
url = "/platform/spatial"
parent = "Platform"
weight = 2

[[main]]
name = "Foundation"
url = "/platform/foundation"
parent = "Platform"
weight = 3

[[main]]
name = "Applications"
weight = 3
hasChildren = true

[[main]]
name = "Robotics"
url = "/applications/robotics"
parent = "Applications"
weight = 1

[[main]]
name = "Simulation"
url = "/applications/simulation"
parent = "Applications"
weight = 2

[[main]]
name = "Digital Twins"
url = "/applications/digital-twins"
parent = "Applications"
weight = 3

[[main]]
name = "Manufacturing"
url = "/applications/manufacturing"
parent = "Applications"
weight = 4

[[main]]
name = "Construction"
url = "/applications/construction"
parent = "Applications"
weight = 5

[[main]]
name = "Government"
url = "/applications/government"
parent = "Applications"
weight = 6

[[main]]
name = "Healthcare"
url = "/applications/healthcare"
parent = "Applications"
weight = 7

[[main]]
name = "Financial"
url = "/applications/financial"
parent = "Applications"
weight = 8

[[main]]
name = "Education"
url = "/applications/education"
parent = "Applications"
weight = 9

[[main]]
name = "Insurance"
url = "/applications/insurance"
parent = "Applications"
weight = 10

[[main]]
name = "Company"
weight = 4
hasChildren = true

[[main]]
name = "Our Story"
url = "/company/story"
parent = "Company"
weight = 1

[[main]]
name = "Experience"
url = "/company/experience"
parent = "Company"
weight = 2

[[main]]
name = "Team"
url = "/company/team"
parent = "Company"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6


# footer menu
[[footer]]
name = "Platform"
url = "/platform"
weight = 1

[[footer]]
name = "Our Story"
url = "/company/story"
weight = 2

[[footer]]
name = "Experience"
url = "/company/experience"
weight = 3

[[footer]]
name = "Blog"
url = "/blog"
weight = 4

[[footer]]
name = "Contact"
url = "/contact"
weight = 5

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 6
