############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Platform"
url = "/platform"
weight = 2
hasChildren = true

[[main]]
name = "Publish"
url = "/platform/publish"
parent = "Platform"
weight = 1

[[main]]
name = "Spatial"
url = "/platform/spatial"
parent = "Platform"
weight = 2

[[main]]
name = "Foundation"
url = "/platform/foundation"
parent = "Platform"
weight = 3

[[main]]
name = "Applications"
url = "/applications"
weight = 3
hasChildren = true

[[main]]
name = "Overview"
identifier = "applications-overview"
url = "/applications"
parent = "Applications"
weight = 1

[[main]]
name = "Robotics"
identifier = "applications-robotics"
url = "/applications/robotics"
parent = "Applications"
weight = 2

[[main]]
name = "Simulation"
url = "/applications/simulation"
parent = "Applications"
weight = 3

[[main]]
name = "Digital Twins"
url = "/applications/digital-twins"
parent = "Applications"
weight = 4

[[main]]
name = "Manufacturing"
url = "/applications/manufacturing"
parent = "Applications"
weight = 5

[[main]]
name = "Construction"
url = "/applications/construction"
parent = "Applications"
weight = 6

[[main]]
name = "Government"
url = "/applications/government"
parent = "Applications"
weight = 7

[[main]]
name = "Healthcare"
url = "/applications/healthcare"
parent = "Applications"
weight = 8

[[main]]
name = "Financial"
url = "/applications/financial"
parent = "Applications"
weight = 9

[[main]]
name = "Education"
url = "/applications/education"
parent = "Applications"
weight = 10

[[main]]
name = "Insurance"
url = "/applications/insurance"
parent = "Applications"
weight = 11

[[main]]
name = "Technology"
url = "/technology"
weight = 4
hasChildren = true

[[main]]
name = "Overview"
identifier = "technology-overview"
url = "/technology"
parent = "Technology"
weight = 1

[[main]]
name = "Robotics"
identifier = "technology-robotics"
url = "/technology/robotics"
parent = "Technology"
weight = 2

[[main]]
name = "Linux & Cross-Platform"
identifier = "technology-linux"
url = "/technology/linux"
parent = "Technology"
weight = 3

[[main]]
name = "Security"
identifier = "technology-security"
url = "/technology/security"
parent = "Technology"
weight = 4

[[main]]
name = "Company"
weight = 5
hasChildren = true

[[main]]
name = "Overview"
identifier = "company-overview"
url = "/company"
parent = "Company"
weight = 1

[[main]]
name = "Experience"
url = "/company/experience"
parent = "Company"
weight = 2

[[main]]
name = "Founder"
url = "/company/founder"
parent = "Company"
weight = 3

[[main]]
name = "Advisors"
url = "/company/advisors"
parent = "Company"
weight = 4

[[main]]
name = "Blog"
url = "/blog"
weight = 6

[[main]]
name = "Contact"
url = "/contact"
weight = 7


# footer menu
[[footer]]
name = "Platform"
url = "/platform"
weight = 1

[[footer]]
name = "Get Started"
url = "/get-started"
weight = 2

[[footer]]
name = "Founder"
url = "/company/founder"
weight = 3

[[footer]]
name = "Experience"
url = "/company/experience"
weight = 4

[[footer]]
name = "Blog"
url = "/blog"
weight = 5

[[footer]]
name = "Contact"
url = "/contact"
weight = 6

[[footer]]
name = "Security"
url = "/security"
weight = 7

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 8
