############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Products"
url = "/product"
weight = 3

[[main]]
name = "Services"
weight = 4
hasChildren = true

[[main]]
name = "Consulting"
url = "/services"
parent = "Services"
weight = 1

[[main]]
name = "Portfolio"
url = "/portfolio"
parent = "Services"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Services"
url = "/services"
weight = 2

[[footer]]
name = "Contact"
url = "/contact"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 4
