############# Thai navigation ##############

# main menu
[[main]]
name = "หน้าแรก"
url = "/"
weight = 1

[[main]]
name = "เกี่ยวกับเรา"
url = "/about"
weight = 2

[[main]]
name = "ผลิตภัณฑ์"
url = "/product"
weight = 3

[[main]]
name = "บริการ"
url = "/services"
weight = 4

[[main]]
name = "ผลงาน"
url = "/portfolio"
weight = 5

[[main]]
name = "บล็อก"
url = "/blog"
weight = 6

[[main]]
name = "ติดต่อเรา"
url = "/contact"
weight = 7


# footer menu
[[footer]]
name = "เกี่ยวกับเรา"
url = "/about"
weight = 1

[[footer]]
name = "บริการ"
url = "/services"
weight = 2

[[footer]]
name = "ติดต่อเรา"
url = "/contact"
weight = 3

[[footer]]
name = "นโยบายความเป็นส่วนตัว"
url = "/privacy-policy"
weight = 4
