############# German navigation ##############

# main menu
[[main]]
name = "Startseite"
url = "/"
weight = 1

[[main]]
name = "Über uns"
url = "/about"
weight = 2

[[main]]
name = "Leistungen"
weight = 3
hasChildren = true

[[main]]
name = "Produkt"
url = "/product"
parent = "Leistungen"
weight = 1

[[main]]
name = "Beratung"
url = "/services"
parent = "Leistungen"
weight = 2

[[main]]
name = "Portfolio"
url = "/portfolio"
parent = "Leistungen"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Kontakt"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "Über uns"
url = "/about"
weight = 1

[[footer]]
name = "Dienstleistungen"
url = "/services"
weight = 2

[[footer]]
name = "Kontakt"
url = "/contact"
weight = 3

[[footer]]
name = "Datenschutz"
url = "/privacy-policy"
weight = 4
