############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Platform"
url = "/platform"
weight = 2
hasChildren = true

[[main]]
name = "Publish"
url = "/platform/publish"
parent = "Platform"
weight = 1

[[main]]
name = "Spatial"
url = "/platform/spatial"
parent = "Platform"
weight = 2

[[main]]
name = "Applications"
weight = 3
hasChildren = true

[[main]]
name = "Robotics"
url = "/applications/robotics"
parent = "Applications"
weight = 1

[[main]]
name = "Simulation"
url = "/applications/simulation"
parent = "Applications"
weight = 2

[[main]]
name = "Digital Twins"
url = "/applications/digital-twins"
parent = "Applications"
weight = 3

[[main]]
name = "Manufacturing"
url = "/applications/manufacturing"
parent = "Applications"
weight = 4

[[main]]
name = "Construction"
url = "/applications/construction"
parent = "Applications"
weight = 5

[[main]]
name = "Company"
weight = 4
hasChildren = true

[[main]]
name = "Our Story"
url = "/company/story"
parent = "Company"
weight = 1

[[main]]
name = "Experience"
url = "/company/experience"
parent = "Company"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6


# footer menu
[[footer]]
name = "Platform"
url = "/platform"
weight = 1

[[footer]]
name = "Applications"
url = "/applications"
weight = 2

[[footer]]
name = "Contact"
url = "/contact"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 4
