############# Chinese navigation ##############

# main menu
# Note: "Home" removed - logo already links to home, saves nav space

[[main]]
name = "平台"
url = "/platform"
weight = 2
hasChildren = true

[[main]]
name = "发布"
url = "/platform/publish"
parent = "平台"
weight = 1

[[main]]
name = "空间"
url = "/platform/spatial"
parent = "平台"
weight = 2

[[main]]
name = "基础"
url = "/platform/foundation"
parent = "平台"
weight = 3

[[main]]
name = "传感"
url = "/platform/sensing"
parent = "平台"
weight = 4

[[main]]
name = "应用"
url = "/applications"
weight = 3
hasChildren = true

[[main]]
name = "概览"
identifier = "applications-overview"
url = "/applications"
parent = "应用"
weight = 1

[[main]]
name = "机器人"
identifier = "applications-robotics"
url = "/applications/robotics"
parent = "应用"
weight = 2

[[main]]
name = "仿真"
url = "/applications/simulation"
parent = "应用"
weight = 3

[[main]]
name = "数字孪生"
url = "/applications/digital-twins"
parent = "应用"
weight = 4

[[main]]
name = "制造业"
url = "/applications/manufacturing"
parent = "应用"
weight = 5

[[main]]
name = "建筑"
url = "/applications/construction"
parent = "应用"
weight = 6

[[main]]
name = "政府"
url = "/applications/government"
parent = "应用"
weight = 7

[[main]]
name = "医疗"
url = "/applications/healthcare"
parent = "应用"
weight = 8

[[main]]
name = "金融"
url = "/applications/financial"
parent = "应用"
weight = 9

[[main]]
name = "教育"
url = "/applications/education"
parent = "应用"
weight = 10

[[main]]
name = "保险"
url = "/applications/insurance"
parent = "应用"
weight = 11

[[main]]
name = "技术"
url = "/technology"
weight = 4
hasChildren = true

[[main]]
name = "概览"
identifier = "technology-overview"
url = "/technology"
parent = "技术"
weight = 1

[[main]]
name = "机器人"
identifier = "technology-robotics"
url = "/technology/robotics"
parent = "技术"
weight = 2

[[main]]
name = "Linux与跨平台"
identifier = "technology-linux"
url = "/technology/linux"
parent = "技术"
weight = 3

[[main]]
name = "安全"
identifier = "technology-security"
url = "/technology/security"
parent = "技术"
weight = 4

[[main]]
name = "公司"
weight = 5
hasChildren = true

[[main]]
name = "概览"
identifier = "company-overview"
url = "/company"
parent = "公司"
weight = 1

[[main]]
name = "经验"
url = "/company/experience"
parent = "公司"
weight = 2

[[main]]
name = "创始人"
url = "/company/founder"
parent = "公司"
weight = 3

[[main]]
name = "顾问"
url = "/company/advisors"
parent = "公司"
weight = 4

[[main]]
name = "博客"
url = "/blog"
weight = 6

[[main]]
name = "联系我们"
url = "/contact"
weight = 7


# footer menu
[[footer]]
name = "平台"
url = "/platform"
weight = 1

[[footer]]
name = "开始使用"
url = "/get-started"
weight = 2

[[footer]]
name = "创始人"
url = "/company/founder"
weight = 3

[[footer]]
name = "经验"
url = "/company/experience"
weight = 4

[[footer]]
name = "博客"
url = "/blog"
weight = 5

[[footer]]
name = "联系我们"
url = "/contact"
weight = 6

[[footer]]
name = "安全"
url = "/security"
weight = 7

[[footer]]
name = "隐私政策"
url = "/privacy-policy"
weight = 8

