############# Japanese navigation ##############

# main menu
[[main]]
name = "ホーム"
url = "/"
weight = 1

[[main]]
name = "会社概要"
url = "/about"
weight = 2

[[main]]
name = "サービス"
weight = 3
hasChildren = true

[[main]]
name = "製品"
url = "/product"
parent = "サービス"
weight = 1

[[main]]
name = "コンサルティング"
url = "/services"
parent = "サービス"
weight = 2

[[main]]
name = "ポートフォリオ"
url = "/portfolio"
parent = "サービス"
weight = 3

[[main]]
name = "ブログ"
url = "/blog"
weight = 4

[[main]]
name = "お問い合わせ"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "会社概要"
url = "/about"
weight = 1

[[footer]]
name = "サービス"
url = "/services"
weight = 2

[[footer]]
name = "お問い合わせ"
url = "/contact"
weight = 3

[[footer]]
name = "プライバシーポリシー"
url = "/privacy-policy"
weight = 4
