############# Swedish navigation ##############

# main menu
[[main]]
name = "Hem"
url = "/"
weight = 1

[[main]]
name = "Om oss"
url = "/about"
weight = 2

[[main]]
name = "Tjänster"
weight = 3
hasChildren = true

[[main]]
name = "Produkt"
url = "/product"
parent = "Tjänster"
weight = 1

[[main]]
name = "Konsulting"
url = "/services"
parent = "Tjänster"
weight = 2

[[main]]
name = "Portfolio"
url = "/portfolio"
parent = "Tjänster"
weight = 3

[[main]]
name = "Blogg"
url = "/blog"
weight = 4

[[main]]
name = "Kontakt"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "Om oss"
url = "/about"
weight = 1

[[footer]]
name = "Tjänster"
url = "/services"
weight = 2

[[footer]]
name = "Kontakt"
url = "/contact"
weight = 3

[[footer]]
name = "Integritetspolicy"
url = "/privacy-policy"
weight = 4
