############# German navigation ##############

# main menu
[[main]]
name = "Startseite"
url = "/"
weight = 1

[[main]]
name = "Über uns"
url = "/about"
weight = 2

[[main]]
name = "Produkt"
url = "/product"
weight = 3

[[main]]
name = "Dienstleistungen"
url = "/services"
weight = 4

[[main]]
name = "Portfolio"
url = "/portfolio"
weight = 5

[[main]]
name = "Blog"
url = "/blog"
weight = 6

[[main]]
name = "Kontakt"
url = "/contact"
weight = 7


# footer menu
[[footer]]
name = "Über uns"
url = "/about"
weight = 1

[[footer]]
name = "Dienstleistungen"
url = "/services"
weight = 2

[[footer]]
name = "Kontakt"
url = "/contact"
weight = 3

[[footer]]
name = "Datenschutz"
url = "/privacy-policy"
weight = 4
